### ISSUE TITLE
GAME MAP

### ISSUE THREAD

**Issue by Medic1111** [harrisxo/browsergame#30]
In order to accomplish this Epic the team must:

- [x] Render a map (perhaps section with divs for each block)
- [x] Identify and track each box somehow
- [x] Have an onclick that displays identifier
- [x] Store the blocks and status possibly in array of objects? To be discussed
- [x] DB must find a way to track boxes, whether occupied or free
- [x] Map is to be sent on Register and Login Route
- [x] Client must be able to read and render the map sent by the server
