### ISSUE TITLE
Structure USER object

### ISSUE THREAD

**Issue by Medic1111** [harrisxo/browsergame#31]
A user model is needed, and Data modeling must take place ASAP

- [x] User credentials info
- [x] User current Army Available (units)
- [x] User current Army In Battle (units)
- [x] User Current Map, and Map Status
- [x] Track Time (user gets x amount of Army Units per x hrs)
