### ISSUE TITLE
RANKING

### ISSUE THREAD

**Issue by Medic1111** [harrisxo/browsergame#33]
In order to accomplish this EPIC the Team must

- [x] Client side render a component that displays the ranking
- [x] It will be fetched from the API
- [x] Server will create route to serve that data
- [x] Data must be sorted to provide Higher to Lower
