### ISSUE TITLE
SERVER: Security

### ISSUE THREAD

**Issue by Medic1111** [harrisxo/browsergame#66]
- [ ] Add HELMET
- [ ] Add rateLimit (against brute force attacks)
- [ ] Add mongoSanitize (agains NOSQL query injections)
- [ ] Add XSS (against xss)
- [ ] Add HPP: (agains params/query pollution)
